### ISSUE TITLE
Different performance of the waymo test between your paper and leaderboard for HEDNet.

### ISSUE THREAD

**Issue by gwenzhang** [zhanggang001/HEDNet#10]
I see that HEDNet gets 76.9/75.0 for mAP/mAPH in your paper. But the result is 75.66/73.77 on the leaderboard.

**Comment by zhanggang001** [comment]
> I see that HEDNet gets 76.9/75.0 for mAP/mAPH in your paper. But the result is 75.66/73.77 on the leaderboard.

**Comment by zhanggang001** [comment]
> I see that HEDNet gets 76.9/75.0 for mAP/mAPH in your paper. But the result is 75.66/73.77 on the leaderboard.

We updated the test results but forgot to publish the new results to the leaderboard. [Here](https://waymo.com/open/challenges/detection-3d/results/6a0c9b2c-7ae6/1694521910913280/)
