### ISSUE TITLE
About 3D-EDB and 2D-EDB

### ISSUE THREAD

**Issue by lebron-2016** [zhanggang001/HEDNet#12]
Hi, does the 3D-EDB mentioned in your paper correspond to `self.sed_layers` in the figure below, and does the 2D-EDB correspond to `self.afd_layers`? Thanks!!

![image](https://github.com/zhanggang001/HEDNet/assets/80045218/fe27d941-2274-4bd2-bb20-46f1d9ab6810)

**Comment by zhanggang001** [comment]
> Hi, does the 3D-EDB mentioned in your paper correspond to `self.sed_layers` in the figure below, and does the 2D-EDB correspond to `self.afd_layers`? Thanks!!
> 
> ![image](https://private-user-images.githubusercontent.com/80045218/330737900-fe27d941-2274-4bd2-bb20-46f1d9ab6810.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU4MjQ5NzgsIm5iZiI6MTcxNTgyNDY3OCwicGF0aCI6Ii84MDA0NTIxOC8zMzA3Mzc5MDAtZmUyN2Q5NDEtMjI3NC00YmQyLWJiMjAtNDZmMWQ5YWI2ODEwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE2VDAxNTc1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZhMTZiNDdmNjYzMGY5OTEyNTdkODRlMDBiZTBmYmVjMGQzYjllOTMxZTZhNGNiNDNkY2UwOWRmMzU2MDkxZWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.-11tpDAig_TWZRA18oCfhWkQVq1-AbFRhjZvA_TtpCc)

Yes!
