### ISSUE TITLE
About safdnet_20e_nuscenes.yaml

### ISSUE THREAD

**Issue by zheng0819** [zhanggang001/HEDNet#13]
Thank you for releasing the code. Regarding safdnet_20e_nuscenes.yaml, I have a question about whether the file nuscenes_10sweeps_withvelo_lidar.npy on line 17 is correct. Because during the generation of NuScenes files, there is no nuscenes_10sweeps_withvelo_lidar.npy file generated.

**Comment by zhanggang001** [comment]
> Thank you for releasing the code. Regarding safdnet_20e_nuscenes.yaml, I have a question about whether the file nuscenes_10sweeps_withvelo_lidar.npy on line 17 is correct. Because during the generation of NuScenes files, there is no nuscenes_10sweeps_withvelo_lidar.npy file generated.
```
python -m pcdet.datasets.nuscenes.nuscenes_dataset --func create_nuscenes_infos \
    --cfg_file tools/cfgs/dataset_configs/nuscenes_dataset.yaml \
    --version v1.0-trainval \
    --share_memory 
 ```
 
 Add the last line to use share memory.
