### ISSUE TITLE
About the detection head

### ISSUE THREAD

**Issue by lebron-2016** [zhanggang001/HEDNet#14]
Hi, when predicting the final heatmap and object size, it looks like you are using normal convolution. Why not use sparse convolution here?

![image](https://github.com/zhanggang001/HEDNet/assets/80045218/1e94faa2-e938-4f9f-a7aa-185f49f03d12)

**Comment by zhanggang001** [comment]
> Hi, when predicting the final heatmap and object size, it looks like you are using normal convolution. Why not use sparse convolution here?
> 
> ![image](https://private-user-images.githubusercontent.com/80045218/331596920-1e94faa2-e938-4f9f-a7aa-185f49f03d12.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYwMTU0NDgsIm5iZiI6MTcxNjAxNTE0OCwicGF0aCI6Ii84MDA0NTIxOC8zMzE1OTY5MjAtMWU5NGZhYTItZTkzOC00ZjlmLWE3YWEtMTg1ZjQ5ZjAzZDEyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE4VDA2NTIyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY4YWY5MzFlOTBlOTA1NjFkNWYyOWE3Y2NjNmEzY2QyZDE4NzQyNDE3MGIzZDhmODg3NTNlY2UwNTZmMjgyMzkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.1r-9tcJliuJRSws63R6Q4PP_RhTVXRkySZRc675gK-E)

It's Conv1d, applied to the queries.
