### ISSUE TITLE
Where is the cfg_file?

### ISSUE THREAD

**Issue by ZhaZhahe** [zhanggang001/HEDNet#2]

**Comment by qifeng22** [comment]
I think this URL maybe waymo cfg file. [https://github.com/zhanggang001/HEDNet/blob/master/tools/cfgs/hednet_models/hednet_8x_1f_onestage_D1_2x.yaml](url)

**Comment by zhanggang001** [comment]
> I think this URL maybe waymo cfg file. [https://github.com/zhanggang001/HEDNet/blob/master/tools/cfgs/hednet_models/hednet_8x_1f_onestage_D1_2x.yaml](url)

Yeah, thank you!
