### ISSUE TITLE
Hello, can you provide the log file in HEDNet and SAFDNet training process?

### ISSUE THREAD

**Issue by yinheyanxian** [zhanggang001/HEDNet#20]
Hello, can you provide the log file in HEDNet and SAFDNet training process?

**Comment by yinheyanxian** [comment]
> 看看我的工程，吊打目前所有的3D目标检测
> 
> 哈哈
> 
> https://github.com/rubbish001/Co-Fix3d
> 
> 
> 
> 中稿就提供训练日志

等大佬开源，我们工程领域又能再水一篇啦🤣

**Comment by zhanggang001** [comment]
> Hello, can you provide the log file in HEDNet and SAFDNet training process?

Sorry for the late reply. The log file has been provided yesterday.
