### ISSUE TITLE
Why is it faster?

### ISSUE THREAD

**Issue by yinheyanxian** [zhanggang001/HEDNet#21]
Hello, thank you for the open source code.

After reading your article and code, I have a question. Why is it faster on the Argo2 dataset than VoxelNeXt?

SAFDNet has significantly more Sparse convolutions and Sparse residual blocks than VoxelNeXt, which leads to better results, but why is it faster?

**Comment by zhanggang001** [comment]
> Hello, thank you for the open source code.
> 
> After reading your article and code, I have a question. Why is it faster on the Argo2 dataset than VoxelNeXt?
> 
> SAFDNet has significantly more Sparse convolutions and Sparse residual blocks than VoxelNeXt, which leads to better results, but why is it faster?

VoxelNeXt is faster than SFADNet (Table 5 of the paper). We do not claim that SAFDNet is faster than VoxelNeXt.

**Comment by yinheyanxian** [comment]
> > Hello, thank you for the open source code.
> > After reading your article and code, I have a question. Why is it faster on the Argo2 dataset than VoxelNeXt?
> > SAFDNet has significantly more Sparse convolutions and Sparse residual blocks than VoxelNeXt, which leads to better results, but why is it faster?
> 
> VoxelNeXt is faster than SFADNet (Table 5 of the paper). We do not claim that SAFDNet is faster than VoxelNeXt.

Sorry, I made a mistake
