### ISSUE TITLE
FLOPs calculation

### ISSUE THREAD

**Issue by meilongzhang** [zhanggang001/HEDNet#24]
Hello, may I ask how the FLOPs calculations for the SAFDNet ablation studies were computed? Thank you very much!

**Comment by zhanggang001** [comment]
> Hello, may I ask how the FLOPs calculations for the SAFDNet ablation studies were computed? Thank you very much!

1. Calculate the FLOPs `T` of `dense` afd_layers and `dense` head (using dense feature maps)
2. Calculate the average sparsity `S`
3. Calculate The approximate FLOPs `T`x`S`
