### ISSUE TITLE
Questions about the waymo_fast_eval

### ISSUE THREAD

**Issue by asd291614761** [zhanggang001/HEDNet#26]
In waymo_fast_eval, a gt.bin file is required, but the author did not provide this file, which makes this function unavailable. I tried to use the convert_pkl_file_to_bin function provided in the source code to convert gt.pkl to gt.bin, but an error message appeared. Can the author provide the gt.bin file? If so, I would be very grateful.

**Comment by asd291614761** [comment]
In addition, according to the code of the latest dev branch, the size of voxel on nuscenes is [0.3,0.3,8.0], but in the paper it is [0.075,0.075,0.2]. Why is this? Second, you only introduced centerhead in the paper, but you used transFusionHead in nuscenes. Why?

**Comment by zhanggang001** [comment]
> In waymo_fast_eval, a gt.bin file is required, but the author did not provide this file, which makes this function unavailable. I tried to use the convert_pkl_file_to_bin function provided in the source code to convert gt.pkl to gt.bin, but an error message appeared. Can the author provide the gt.bin file? If so, I would be very grateful.

Download here
[compute_detection_metrics_main](https://cloud.tsinghua.edu.cn/f/df1c6c0b629b4929a357/?dl=1)
[gt.bin](https://cloud.tsinghua.edu.cn/f/637df33ef3a44fd09fb8/?dl=1)

**Comment by zhanggang001** [comment]
> In addition, according to the code of the latest dev branch, the size of voxel on nuscenes is [0.3,0.3,8.0], but in the paper it is [0.075,0.075,0.2]. Why is this? Second, you only introduced centerhead in the paper, but you used transFusionHead in nuscenes. Why?

I'm sorry to tell you that these are the two mistakes we made in the paper:

1. We indeed used the TransFusion-L head on the nuScenes dataset, following HEDNet. In the paper, we only introduce CenterPoint to simplify the description (since the TransFusion-L Head also relies on the CenterPoint classification heatmap to initialize the query, and our adjustments to both heads are made on the classification heatmap), but this might indeed mislead readers. We will clarify this in the updated version of the paper as soon as possible.

2. SAFDNet is a follow-up work of HEDNet. We initially implemented HEDNet on the nuScenes dataset (based on TransFusion-L) using MMDetection3D and on the Waymo Open dataset (based on CenterPoint) using OpenPCDet. The TransFusion-L uses a 3D hierarchical sparse backbone with a voxel size of [0.075, 0.075, 0.2].  However, the original implementation in OpenPCDet achieved worse results than that in MMDetection3D. To unify the codebase with OpenPCDet, we adopted a 2D single-stride sparse backbone (voxel size [0.3, 0.3, 8.0]), which achieved similar results to the hierarchical one in MMDetection3D, for both SAFDNet and HEDNet on the nuScenes dataset in the release code. In the paper, we directly borrowed the experimental settings from the HEDNet paper, and some mistakes were carried over. We will correct these in the updated version of the paper. Please follow the settings in the released code to run your experiments.

**Comment by asd291614761** [comment]
d

> > In addition, according to the code of the latest dev branch, the size of voxel on nuscenes is [0.3,0.3,8.0], but in the paper it is [0.075,0.075,0.2]. Why is this? Second, you only introduced centerhead in the paper, but you used transFusionHead in nuscenes. Why?
> 
> I'm sorry to tell you that these are the two mistakes we made in the paper:
> 
> 1. We indeed used the TransFusion-L head on the nuScenes dataset, following HEDNet. In the paper, we only introduce CenterPoint to simplify the description (since the TransFusion-L Head also relies on the CenterPoint classification heatmap to initialize the query, and our adjustments to both heads are made on the classification heatmap), but this might indeed mislead readers. We will clarify this in the updated version of the paper as soon as possible.
> 2. SAFDNet is a follow-up work of HEDNet. We initially implemented HEDNet on the nuScenes dataset (based on TransFusion-L) using MMDetection3D and on the Waymo Open dataset (based on CenterPoint) using OpenPCDet. The TransFusion-L uses a 3D hierarchical sparse backbone with a voxel size of [0.075, 0.075, 0.2].  However, the original implementation of TransFusion-L in OpenPCDet achieved worse results than that in MMDetection3D. To unify the codebase with OpenPCDet, we adopted a 2D single-stride sparse backbone (voxel size [0.3, 0.3, 8.0]) for both SAFDNet and HEDNet on the nuScenes dataset in the release code (The single-stride HEDNet achieved similar results to the hierarchical one in MMDetection3D). In the paper, we directly borrowed the experimental settings from the HEDNet paper, and some mistakes were carried over. We will correct these in the updated version of the paper. Please follow the settings in the released code to run your experiments.

Thank you for your reply. Currently, there is still an issue with the operation. Specifically, an error occurred while running the computed_detection_stetrics_main executable file. But without the source code, I cannot view the specific error message. What should I do in this situation

**Comment by zhanggang001** [comment]
> d
> 
> > > In addition, according to the code of the latest dev branch, the size of voxel on nuscenes is [0.3,0.3,8.0], but in the paper it is [0.075,0.075,0.2]. Why is this? Second, you only introduced centerhead in the paper, but you used transFusionHead in nuscenes. Why?
> > 
> > 
> > I'm sorry to tell you that these are the two mistakes we made in the paper:
> > 
> > 1. We indeed used the TransFusion-L head on the nuScenes dataset, following HEDNet. In the paper, we only introduce CenterPoint to simplify the description (since the TransFusion-L Head also relies on the CenterPoint classification heatmap to initialize the query, and our adjustments to both heads are made on the classification heatmap), but this might indeed mislead readers. We will clarify this in the updated version of the paper as soon as possible.
> > 2. SAFDNet is a follow-up work of HEDNet. We initially implemented HEDNet on the nuScenes dataset (based on TransFusion-L) using MMDetection3D and on the Waymo Open dataset (based on CenterPoint) using OpenPCDet. The TransFusion-L uses a 3D hierarchical sparse backbone with a voxel size of [0.075, 0.075, 0.2].  However, the original implementation of TransFusion-L in OpenPCDet achieved worse results than that in MMDetection3D. To unify the codebase with OpenPCDet, we adopted a 2D single-stride sparse backbone (voxel size [0.3, 0.3, 8.0]) for both SAFDNet and HEDNet on the nuScenes dataset in the release code (The single-stride HEDNet achieved similar results to the hierarchical one in MMDetection3D). In the paper, we directly borrowed the experimental settings from the HEDNet paper, and some mistakes were carried over. We will correct these in the updated version of the paper. Please follow the settings in the released code to run your experiments.
> 
> Thank you for your reply. Currently, there is still an issue with the operation. Specifically, an error occurred while running the computed_detection_stetrics_main executable file. But without the source code, I cannot view the specific error message. What should I do in this situation

chmod +x computed_detection_stetrics_main
