### ISSUE TITLE
Why use pillar in nuScenes but not voxel?

### ISSUE THREAD

**Issue by Raiden-cn** [zhanggang001/HEDNet#27]
In the appendix A of  paper [HEDNet](https://arxiv.org/pdf/2310.20234), "We adopted the detection head of TransFusion-L [28]
for HEDNet and primarily followed the training and inference schemes of TransFusion-L [28]. The voxel size was set to (0.075m, 0.075m, 0.2m)" has been mentioned. 
It seems a mistake or I miss something?

**Comment by Raiden-cn** [comment]
I found [another repo](https://github.com/zhanggang001/HEDNet-nusc) of yours, where it use voxel. And the performance only drops slightly shown in README. Could you give me a hint about the reason? 

Looking forward the reply.

**Comment by zhanggang001** [comment]
> In the appendix A of paper [HEDNet](https://arxiv.org/pdf/2310.20234), "We adopted the detection head of TransFusion-L [28] for HEDNet and primarily followed the training and inference schemes of TransFusion-L [28]. The voxel size was set to (0.075m, 0.075m, 0.2m)" has been mentioned. It seems a mistake or I miss something?

The HEDNet adopts the detection pipeline of TransFusion-L. The original implementation of HEDNet on the nuScenes dataset in the paper indeed adopts a voxel size of (0.075m, 0.075m, 0.2m) ([this repo](https://github.com/zhanggang001/HEDNet-nusc) based on MMDetection3D). However, the voxel version of TransFusion-L in OpenPCDet achieves worse results than that in MMDetection3D. To unify the codebase of HEDNet on all datasets using OpenPCDet, we release a pillar version of HEDNet on the nuScenes dataset, which performs comparably to the voxel version in MMDetection3D.

**Comment by Raiden-cn** [comment]
Got it! Thx for the reply.
