### ISSUE TITLE
About the code of diffusion function in SAFDNet.

### ISSUE THREAD

**Issue by Raiden-cn** [zhanggang001/HEDNet#28]
Why the [max pooling](https://github.com/zhanggang001/HEDNet/blob/4ef7b536a40d8caf306035a15fb82cebd3aa5ce6/pcdet/models/backbones_3d/hednet.py#L452) contains bg_group?
Following the fig.4 of [SAFDNet](https://arxiv.org/abs/2403.05817), the bg voxels should not be diffused.
If I'm not mistaken,  [max pooling](https://github.com/zhanggang001/HEDNet/blob/4ef7b536a40d8caf306035a15fb82cebd3aa5ce6/pcdet/models/backbones_3d/hednet.py#L452) is to diffuse voxels as described in AFD.

Looking forward your reply!

**Comment by Raiden-cn** [comment]
I post a example as following, which occur in the initial stage of training:
medium:5-->360 large:17-->1149 small:0 bg:9964-->18701  total:18701
Those number are number of voxels, and the medium, large, small are defined by [here](https://github.com/zhanggang001/HEDNet/blob/4ef7b536a40d8caf306035a15fb82cebd3aa5ce6/tools/cfgs/safdnet_models/safdnet_20e_nuscenes.yaml#L91), bg means background voxel which below the [fg_thr](https://github.com/zhanggang001/HEDNet/blob/4ef7b536a40d8caf306035a15fb82cebd3aa5ce6/pcdet/models/backbones_3d/hednet.py#L438).
Although the threshold will be more precise as training and the number of background voxels will decrease, I can't deny the code conflicts with the paper if I didn't make mistake.

Looking forward your reply!

**Comment by zhanggang001** [comment]
> Why the [max pooling](https://github.com/zhanggang001/HEDNet/blob/4ef7b536a40d8caf306035a15fb82cebd3aa5ce6/pcdet/models/backbones_3d/hednet.py#L452) contains bg_group? Following the fig.4 of [SAFDNet](https://arxiv.org/abs/2403.05817), the bg voxels should not be diffused. If I'm not mistaken, [max pooling](https://github.com/zhanggang001/HEDNet/blob/4ef7b536a40d8caf306035a15fb82cebd3aa5ce6/pcdet/models/backbones_3d/hednet.py#L452) is to diffuse voxels as described in AFD.
> 
> Looking forward your reply!

Fig.4 is an example, and it does not indicate that 'the bg voxels should not be diffused'. I admit this looks like a trick in our writing process (to highlight the `sparse` feature maps), but we have presented the implementation details in the Appendix.

It's worth noting that the SAFDNet is proposed to improve the model efficiency on long-range perception scenarios. On the Argoverse2 dataset with a long perception range, setting the diffusion range of background voxels to zero yields results similar to those obtained with diffusion (the released one). On the Waymo Open and nuScenes datasets, which have a shorter perception range, setting the diffusion range of background voxels to zero slightly degrades performance.

**Comment by Raiden-cn** [comment]
Got it. It's great work!
