### ISSUE TITLE
About argo2_dbinfos.pkl

### ISSUE THREAD

**Issue by seonhoon1002** [zhanggang001/HEDNet#29]
Hello, I'd like to run the Argoverse dataset with your code, but I have bug that argo2_dbinfos.pkl file is missing. The installation method for the dataset only mentions the installation of pkl files for train and test. Could you please let me know how to handle the argo2_dbinfos.pkl issue?

**Comment by zhanggang001** [comment]
> Hello, I'd like to run the Argoverse dataset with your code, but I have bug that argo2_dbinfos.pkl file is missing. The installation method for the dataset only mentions the installation of pkl files for train and test. Could you please let me know how to handle the argo2_dbinfos.pkl issue?

Do you run the latest main branch? I updated it yesterday.

**Comment by seonhoon1002** [comment]
I found update at argo2_dataset last update, I will try make the dataset again.

**Comment by seonhoon1002** [comment]
> > Hello, I'd like to run the Argoverse dataset with your code, but I have bug that argo2_dbinfos.pkl file is missing. The installation method for the dataset only mentions the installation of pkl files for train and test. Could you please let me know how to handle the argo2_dbinfos.pkl issue?
> 
> Do you run the latest main branch? I updated it yesterday.

Updated code works for me, but I have more problem like this

```
2024-09-22 10:30:40,482   INFO  **********************Start training safdnet_models/safdnet_1f_2x_argo(default)**********************
epochs:   0%|          | 0/24 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/cv-00/anaconda3/envs/dice_dna/lib/python3.9/multiprocessing/spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "/home/cv-00/anaconda3/envs/dice_dna/lib/python3.9/multiprocessing/spawn.py", line 126, in _main
    self = reduction.pickle.load(from_parent)
_pickle.UnpicklingError: pickle data was truncated
```

These errors occur both "waymo" and "argoverse"

I heard these are related memory issues, so I chance the number of worker  4 to 1 but It doesn't work for me(I use 256GB RAM).

Could you please let me know how to handle this problem?

**Comment by zhanggang001** [comment]
> > > Hello, I'd like to run the Argoverse dataset with your code, but I have bug that argo2_dbinfos.pkl file is missing. The installation method for the dataset only mentions the installation of pkl files for train and test. Could you please let me know how to handle the argo2_dbinfos.pkl issue?
> > 
> > 
> > Do you run the latest main branch? I updated it yesterday.
> 
> Updated code works for me, but I have another problems like this
> 
> ```
> 2024-09-22 10:30:40,482   INFO  **********************Start training safdnet_models/safdnet_1f_2x_argo(default)**********************
> epochs:   0%|          | 0/24 [00:00<?, ?it/s]
> Traceback (most recent call last):
>   File "<string>", line 1, in <module>
>   File "/home/cv-00/anaconda3/envs/dice_dna/lib/python3.9/multiprocessing/spawn.py", line 116, in spawn_main
>     exitcode = _main(fd, parent_sentinel)
>   File "/home/cv-00/anaconda3/envs/dice_dna/lib/python3.9/multiprocessing/spawn.py", line 126, in _main
>     self = reduction.pickle.load(from_parent)
> _pickle.UnpicklingError: pickle data was truncated
> ```
> 
> These errors occur both "waymo" and "argoverse"
> 
> I heard these are related memory issues, so I chance the number of worker 4 to 1 but It doesn't work for me(I use 256GB RAM).
> 
> Could you please let me know how to handle this problem?

Sorry, I haven't encountered this issue before, and I don't believe it is related to SAFDNet. There may be an issue with your environment, as others have been able to run the code successfully.

**Comment by seonhoon1002** [comment]
Ok, I see. Thank you for your anwser. It seems that I need more time to solve it.
