### ISSUE TITLE
Is the network structure of the 3D sparse backbone in SAFDNet the same as that of HEDnet?

### ISSUE THREAD

**Issue by qifeng22** [zhanggang001/HEDNet#30]
Is the improvement in inference time in SAFDNet entirely due to the sparse detection head? Has the SAFDNet backbone been simplified compared to HEDNet? 
@zhanggang001

**Comment by zhanggang001** [comment]
> Is the improvement in inference time in SAFDNet entirely due to the sparse detection head? Has the SAFDNet backbone been simplified compared to HEDNet? @zhanggang001

We did not carefully compare the inference time of the backbones of HEDNet and SAFDNet. 
During training, using both the simplified backbone of SAFDNet and the original backbone of HEDNet yields similar speed and results. We adopt the simplified version for simplicity. The improvement in inference time (entirely or mainly) comes from using the sparse bev backbone and sparse detection head.
