### ISSUE TITLE
'EasyDict' object has no attribute 'BACKUP_DB_INFO'

### ISSUE THREAD

**Issue by qifeng22** [zhanggang001/HEDNet#31]
HEDNet-main/tools/../pcdet/datasets/augmentor/database_sampler.py", line 38, in __init__
    sampler_cfg.DB_INFO_PATH[0] = sampler_cfg.BACKUP_DB_INFO['DB_INFO_PATH']
AttributeError: 'EasyDict' object has no attribute 'BACKUP_DB_INFO'

When I run code, I have this problem.
@zhanggang001

**Comment by zhanggang001** [comment]
> HEDNet-main/tools/../pcdet/datasets/augmentor/database_sampler.py", line 38, in **init** sampler_cfg.DB_INFO_PATH[0] = sampler_cfg.BACKUP_DB_INFO['DB_INFO_PATH'] AttributeError: 'EasyDict' object has no attribute 'BACKUP_DB_INFO'
> 
> When I run code, I have this problem. @zhanggang001

Please carefully follow the instructions to run the code. This error indicates that some files are missing.

**Comment by qifeng22** [comment]
ok，thanks, but when i use single GPU 
python train.py --cfg_file cfgs/safdnet_models/safdnet_1f_1x_waymo.yaml
the error occur

RuntimeError: Default process group has not been initialized, please make sure to call init_process_group
@zhanggang001

**Comment by zhanggang001** [comment]
> ok，thanks, but when i use single GPU python train.py --cfg_file cfgs/safdnet_models/safdnet_1f_1x_waymo.yaml the error occur
> 
> RuntimeError: Default process group has not been initialized, please make sure to call init_process_group @zhanggang001

Please run the code using the training script we provided (in tools/scripts).

**Comment by 666xzy** [comment]
您好，我使用单 GPU python train.py --cfg_file cfgs/safdnet_models/safdnet_1f_1x_waymo.yaml 时出现错误AttributeError: 'EasyDict' object has no attribute 'BACKUP_DB_INFO'

**Comment by qifeng22** [comment]
you can run the code using the training script in tools/scripts by using single GPU, try it. It so long time, i also forger it.
