### ISSUE TITLE
_pickle.UnpicklingError: pickle data was truncated during distributed training with more than 2 GPUs

### ISSUE THREAD

**Issue by qifeng22** [zhanggang001/HEDNet#32]
Hello, I'm encountering an issue when running distributed training with more than 2 GPUs (e.g., 4 GPUs). At the beginning of training, the following error occurs:
![image](https://github.com/user-attachments/assets/9de723e0-6dbc-4b1d-9a61-5c47129b2097)
@zhanggang001

**Comment by qifeng22** [comment]
Here is my memory in ubuntu system.
![image](https://github.com/user-attachments/assets/542b06ee-901b-4ad8-9875-96fd2d61c791)

**Comment by zhanggang001** [comment]
> Hello, I'm encountering an issue when running distributed training with more than 2 GPUs (e.g., 4 GPUs). At the beginning of training, the following error occurs: ![image](https://private-user-images.githubusercontent.com/57132534/375277649-9de723e0-6dbc-4b1d-9a61-5c47129b2097.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg3MTM3MjEsIm5iZiI6MTcyODcxMzQyMSwicGF0aCI6Ii81NzEzMjUzNC8zNzUyNzc2NDktOWRlNzIzZTAtNmRiYy00YjFkLTlhNjEtNWM0NzEyOWIyMDk3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDEyVDA2MTAyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI1NmVhZDk0MWI2NGM0MDlkNTA3MWE5YWI2YTg4NmU2ZDBlYjVkYzIwZWE5ZDZhNjExYTkzOWY2ODQ5NjYwN2ImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.sm8QyNEqfYTAKIJogj6R4NRHn5h2-Zc8OhGfeoLMykE) @zhanggang001

Sorry to tell you, but I don’t think it’s a problem with SAFDNet; it’s related to your usage of OpenPCDet. Others have successfully run the code.

**Comment by qifeng22** [comment]
ok，thanks
