### ISSUE TITLE
Why 'DETACH_FEATURE: True' in the process of Adaptive feature diffusion?

### ISSUE THREAD

**Issue by qifeng22** [zhanggang001/HEDNet#33]
![image](https://github.com/user-attachments/assets/96ab5299-d832-496c-9a08-bc2821bf7827)
@zhanggang001

**Comment by qifeng22** [comment]
If I set False, will it affect the detection accuracy?

**Comment by zhanggang001** [comment]
> If I set False, will it affect the detection accuracy?

Both settings yield similar results, but setting it to True makes the training more stable.

**Comment by qifeng22** [comment]
okok，thanks
