### ISSUE TITLE
waymo submission test augmentation

### ISSUE THREAD

**Issue by seonhoon1002** [zhanggang001/HEDNet#34]
Hello, could you share the cfg file used for the Waymo submission, or if that's difficult, could you provide the test augmentation settings?"

**Comment by zhanggang001** [comment]
> Hello, could you share the cfg file used for the Waymo submission, or if that's difficult, could you provide the test augmentation settings?"

No extra augmentation operations were used for the Waymo submission.  Following the common practice, we use both the training and val sets to train the model and conduct inference on the test set. We also generate the gt_database from both training and val sets.

To achieve this , we do not change the cfg file, but generate the new files ('waymo_processed_data_v0_5_0_infos_train.pkl' and 'waymo_processed_data_v0_5_0_waymo_dbinfos_train_sampled_1.pkl') to cover both training and val sets.

**Comment by seonhoon1002** [comment]
Oh, I understand. Thank you
