### ISSUE TITLE
What is the difference f_center and f_cluster?

### ISSUE THREAD

**Issue by qifeng22** [zhanggang001/HEDNet#4]

**Comment by qifeng22** [comment]
![Uploading 微信图片_20240320220149.png…]()

**Comment by zhanggang001** [comment]
> _No description provided._

f_center is the distance from each point to the voxel center

f_cluster is the distance from each point to the geometric center (the average coordinates of all points inside the voxel)

**Comment by qifeng22** [comment]
okok，I got it. Thanks for your reply.
