### ISSUE TITLE
How to calculate spconv.SparseInverseConv3d in detail mathematically?

### ISSUE THREAD

**Issue by qifeng22** [zhanggang001/HEDNet#5]
@zhanggang001

**Comment by zhanggang001** [comment]
Please refer to the implementation [here](https://github.com/traveller59/spconv/blob/125a194d895b1bc3ad6ff907bc72641548397b32/spconv/pytorch/conv.py#L1103)

**Comment by zhanggang001** [comment]
> @zhanggang001

Please refer to the implementation [here](https://github.com/traveller59/spconv/blob/125a194d895b1bc3ad6ff907bc72641548397b32/spconv/pytorch/conv.py#L1103).

**Comment by qifeng22** [comment]
I have seen it, but I cant undetstand the Implementation details. Specifically, for data that has already been downsampled, what is the way to expand the position of one position element and fill in zeros for all other positions？ @zhanggang001

**Comment by qifeng22** [comment]
SparseInverseConv3d（kernel=3)，在这一步过程中，针对某个位置的元素，如何实现扩展位置元素的，我运行了一个简单代码测试了下，发现是用0 补充的，但是kernel起什么作用。是首先对数据用0补充，然后再对indice位置计算吗？

**Comment by zhanggang001** [comment]
> I have seen it, but I cant undetstand the Implementation details. Specifically, for data that has already been downsampled, what is the way to expand the position of one position element and fill in zeros for all other positions？ @zhanggang001

Actually, I've forgotten the exact implementation now, but I know that each SparseInverseConv3d is paired with one SparseConv3d. The indices used in the paired SparseConv3d are also used in the corresponding SparseInverseConv3d, to make sure that the output indices of the SparseInverseConv3d are the same as those of the paired SparseConv3d.

If I figure it out, I will reply to you.

**Comment by qifeng22** [comment]
okok， thanks for your reply.

**Comment by MSunDYY** [comment]
I think it's to search the position surrounded by 26 nonempty voxels and then conv.
