### ISSUE TITLE
SAFDNet

### ISSUE THREAD

**Issue by MSunDYY** [zhanggang001/HEDNet#8]
I'm very interested in your adapt feature diffusion in SAFDNet and want to study how is it implemented to incorporate it in my work.Please release it soon.
Thanks!

**Comment by zhanggang001** [comment]
> I'm very interested in your adapt feature diffusion in SAFDNet and want to study how is it implemented to incorporate it in my work.Please release it soon. Thanks!

Thanks for your interest! The code has been released.
